package Jun_03rd;


import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sinopall
 */
public class Kantin extends javax.swing.JFrame {

    /**
     * 
     */
    public Kantin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulLbl = new javax.swing.JLabel();
        namaLbl = new javax.swing.JLabel();
        hargaLbl = new javax.swing.JLabel();
        jmlLbl = new javax.swing.JLabel();
        hargaF = new javax.swing.JTextField();
        namaCb = new javax.swing.JComboBox<>();
        jmlF = new javax.swing.JTextField();
        totalBtn = new javax.swing.JButton();
        totalLbl = new javax.swing.JLabel();
        diskonLbl = new javax.swing.JLabel();
        totalF = new javax.swing.JTextField();
        diskonF = new javax.swing.JTextField();
        bayarLbl = new javax.swing.JLabel();
        bayarF = new javax.swing.JTextField();
        kembalianBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        uangLbl = new javax.swing.JLabel();
        uangF = new javax.swing.JTextField();
        kembalianLbl = new javax.swing.JLabel();
        kembalianF = new javax.swing.JTextField();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judulLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        judulLbl.setText("Kantin Avent");

        namaLbl.setText("Nama Barang");

        hargaLbl.setText("Harga");

        jmlLbl.setText("Jumlah Barang");

        hargaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaFActionPerformed(evt);
            }
        });

        namaCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang", "Pena", "Pensil", "Buku", "Penghapus" }));
        namaCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaCbActionPerformed(evt);
            }
        });

        jmlF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlFActionPerformed(evt);
            }
        });

        totalBtn.setText("Hitung Total");
        totalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBtnActionPerformed(evt);
            }
        });

        totalLbl.setText("Total Pembelian");

        diskonLbl.setText("Diskon");

        totalF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFActionPerformed(evt);
            }
        });

        bayarLbl.setText("Total Bayar");

        bayarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarFActionPerformed(evt);
            }
        });

        kembalianBtn.setText("Hitung Kembalian");
        kembalianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        uangLbl.setText("Uang Pembayaran");

        uangF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangFActionPerformed(evt);
            }
        });

        kembalianLbl.setText("Kembalian");

        kembalianF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianFActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bayarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jmlLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(diskonF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(bayarF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmlF, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kembalianLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(uangLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(diskonLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uangF)
                            .addComponent(kembalianF)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(namaLbl)
                        .addGap(37, 37, 37)
                        .addComponent(namaCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kembalianBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hargaLbl)
                        .addGap(18, 18, 18)
                        .addComponent(hargaF, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(judulLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(judulLbl)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaLbl)
                            .addComponent(namaCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaLbl)
                            .addComponent(hargaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jmlLbl)
                            .addComponent(jmlF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLbl)
                            .addComponent(totalF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diskonLbl)
                            .addComponent(diskonF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bayarLbl)
                            .addComponent(bayarF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uangLbl)
                            .addComponent(uangF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kembalianBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kembalianLbl)
                            .addComponent(kembalianF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exitBtn)
                        .addComponent(resetBtn)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hargaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaFActionPerformed

    private void namaCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaCbActionPerformed
        int brg = (int)namaCb.getSelectedIndex();
        switch(brg) {
            case 1: hargaF.setText("15000"); break;
            case 2: hargaF.setText("10000"); break;
            case 3: hargaF.setText("20000"); break;
            case 4: hargaF.setText("75000"); break;
        }
    }//GEN-LAST:event_namaCbActionPerformed

    private void jmlFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlFActionPerformed

    private void totalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBtnActionPerformed
        // Integer.parseInt() -> Mengubah String menjadi int
        int harga = Integer.parseInt(hargaF.getText());
        int jumlah = Integer.parseInt(jmlF.getText());
        double diskon = 0;
        int tb = harga * jumlah;

        // Integer.toString() -> Mengubah int menjadi String
        totalF.setText(Integer.toString(tb));

        if(tb > 100000) {
            diskon = 0.1 * tb;
        }

        diskonF.setText(Double.toString(diskon));

        double tbayar = tb - diskon;

        bayarF.setText(Double.toString(tbayar));
    }//GEN-LAST:event_totalBtnActionPerformed

    private void totalFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFActionPerformed

    }//GEN-LAST:event_totalFActionPerformed

    private void bayarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarFActionPerformed

    private void kembalianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianBtnActionPerformed
        double bayar = Double.parseDouble(uangF.getText());
        double tbayar = Double.parseDouble(bayarF.getText());
        if(bayar < tbayar) {
            JOptionPane.showMessageDialog(this, "Uang anda kurang", "Pesan", 
                    JOptionPane.INFORMATION_MESSAGE);
        }
        double kembali = bayar - tbayar;
        kembalianF.setText(Double.toString(kembali));
    }//GEN-LAST:event_kembalianBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        namaCb.setSelectedIndex(0);
        hargaF.setText("");
        jmlF.setText("");
        totalF.setText("");
        diskonF.setText("");
        bayarF.setText("");
        uangF.setText("");
        kembalianF.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    private void uangFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uangFActionPerformed

    private void kembalianFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianFActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        int pil = JOptionPane.showConfirmDialog(this, "Apakah yakin ingi keluar", 
                "Peringantan", JOptionPane.YES_NO_OPTION);

        if(pil == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kantin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kantin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayarF;
    private javax.swing.JLabel bayarLbl;
    private javax.swing.JTextField diskonF;
    private javax.swing.JLabel diskonLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField hargaF;
    private javax.swing.JLabel hargaLbl;
    private javax.swing.JTextField jmlF;
    private javax.swing.JLabel jmlLbl;
    private javax.swing.JLabel judulLbl;
    private javax.swing.JButton kembalianBtn;
    private javax.swing.JTextField kembalianF;
    private javax.swing.JLabel kembalianLbl;
    private javax.swing.JComboBox<String> namaCb;
    private javax.swing.JLabel namaLbl;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton totalBtn;
    private javax.swing.JTextField totalF;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JTextField uangF;
    private javax.swing.JLabel uangLbl;
    // End of variables declaration//GEN-END:variables
}
